AWSTemplateFormatVersion: '2010-09-09'
Description: Create an EC2 instance with a Security Group

Resources:
  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Allow SSH and HTTP access"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0  # Allow SSH from anywhere (update as needed)
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0  # Allow SSH from anywhere (update as needed)

  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0cb91c7de36eed2cb  # Replace with a valid AMI ID
      SecurityGroupIds:
        - !Ref MySecurityGroup
      KeyName: firstpass # Replace with your key pair
      Tags:
        - Key: Name
          Value: MyEC2Instance